runtime: python39
entrypoint: gunicorn -b :$PORT app:app

handlers:
  - url: /.*
    script: auto

env: standard

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

env_variables:
  DB_USER: "brayan"
  DB_PASSWORD: "brayan0175"
  DB_HOST: "35.238.188.101"
  DB_NAME: "motion"
