runtime: python39
entrypoint: gunicorn -b :$PORT app:app

handlers:
  - url: /.*
    script: auto

env: standard

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

env_variables:
  DB_USER: "root"
  DB_PASSWORD: "brayan1997"
  DB_HOST: "34.176.155.210"
  DB_PORT: "3306"
  DB_NAME: "motion"
