runtime: python39
entrypoint: gunicorn -b :$PORT app:app

handlers:
  - url: /.*
    script: auto

env: standard

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

env_variables:
  DB_USER: "${DB_USER}"  # Cambiar a variables de entorno
  DB_PASSWORD: "${DB_PASSWORD}"
  DB_HOST: "${DB_HOST}"
  DB_PORT: "${DB_PORT}"
  DB_NAME: "${DB_NAME}"
